### PR TITLE
Use cstubs instead of libffi

### PR DESCRIPTION
**Pull request by whitequark**
This almost works.

There are three issues:

  * https://github.com/ocamllabs/ocaml-ctypes/issues/278, which prevents `debug_message_callback` from being available.
  * https://github.com/ocamllabs/ocaml-ctypes/issues/279, which makes some code uglier than it needs to be.
  * The ~stub is missing. This is major; currently the bindings are ~~unusable in practice (but assuming all functions are always present, they would be)~~ using a rather hacky way to get a hold of OpenGL functions.

I'm looking into replacing `~stub`.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Didn't have a close look but how do you solve [this problem](http://lists.ocaml.org/pipermail/ctypes/2014-January/000049.html) ?

**Comment by whitequark** [comment]
This is what I'm currently working on. On desktops we can use [GLEW](http://glew.sourceforge.net/index.html) which does just that inside a C header. Not sure about mobile platforms yet.

**Comment by dbuenzli** [comment]
Arf. I think I prefer to stay away from GLEW and other OpenGL extension loading libraries.

**Comment by whitequark** [comment]
I guess I could extend ctypes. This also solves the GLES problem, where one has to use eglGetProcAddress.

**Comment by whitequark** [comment]
I'm no longer interested in pursuing this as ctypes-foreign can now be easily cross-compiled and this removes most of the problems.

**Pull request closed without merging**
